"""Reading and writing MPQ archives -- enough to open and save a map.

A ``.scm``/``.scx`` map is an MPQ archive with ``staredit\\scenario.chk`` inside
it, so this is what connects the rest of the library to real map files.

**Reading** is deliberately partial: MPQ v1 with encrypted hash and block
tables, multi-sector and single-unit files, ``FIX_KEY``, and the compressions
StarCraft maps actually use. It does not handle v2+ extended tables, and does
not implement compressions no map has ever used (ADPCM, Huffman, sparse) --
those raise rather than returning wrong bytes.

**Writing** produces a minimal, plainly-laid-out v1 archive: header, file data,
hash table, block table. Nothing is encrypted on write, because encryption only
exists to make files hard to extract and buys a map editor nothing.

On write compression, two tools whose output is known to load in StarCraft
disagree, and both are fine:

- ``euddraft``/``eudplib`` -- the toolchain the production UMS scene builds with
  -- writes **zlib** (``MPQ_COMPRESSION_ZLIB``, ``eudplib-stormlib/src/lib.rs``).
- ``sc64-maps`` writes everything **uncompressed**, and those maps were verified
  in-game.

So :class:`MpqWriter` defaults to storing plainly, which is the option nothing
can refuse, and ``compress=True`` opts into zlib on the strength of euddraft's
production use. Writing PKWARE implode -- what Blizzard's own maps use -- would
need a compressor, and only the decompressor is implemented here.

Written from the published format description rather than derived from any
existing implementation, so that this file can be MIT-licensed.

Correctness is established against ground truth rather than by inspection. Every
scenario read here is compared byte-for-byte with StormLib's extraction of the
same file, and every archive written here is handed back to StormLib to reopen.
See ``tests/test_mpq.py``.
"""

from __future__ import annotations

import bz2
import struct
import zlib
from dataclasses import dataclass
from typing import Iterator

from .pkware import explode

__all__ = [
    "MpqArchive", "MpqWriter", "MpqError", "SCENARIO_PATH", "looks_like_mpq",
    "read_scenario", "write_scenario",
]

SCENARIO_PATH = "staredit\\scenario.chk"

MPQ_MAGIC = b"MPQ\x1a"
_USERDATA_MAGIC = b"MPQ\x1b"
#: An archive may be preceded by other data, aligned to a 512-byte boundary.
_ALIGN = 512

_HEADER = struct.Struct("<4sIIHHIIII")
_HASH_ENTRY = struct.Struct("<IIHHI")
_BLOCK_ENTRY = struct.Struct("<IIII")

_HASH_ENTRY_SIZE = 16
_BLOCK_ENTRY_SIZE = 16

# Block flags
FLAG_IMPLODE = 0x00000100      # whole file is PKWARE-imploded, no method byte
FLAG_COMPRESS = 0x00000200     # each sector carries a leading method byte
FLAG_ENCRYPTED = 0x00010000
FLAG_FIX_KEY = 0x00020000
FLAG_SINGLE_UNIT = 0x01000000
FLAG_DELETE_MARKER = 0x02000000
FLAG_SECTOR_CRC = 0x04000000
FLAG_EXISTS = 0x80000000

# Compression method bits, used when FLAG_COMPRESS is set
COMP_HUFFMAN = 0x01
COMP_ZLIB = 0x02
COMP_PKWARE = 0x08
COMP_BZIP2 = 0x10
COMP_SPARSE = 0x20
COMP_ADPCM_MONO = 0x40
COMP_ADPCM_STEREO = 0x80

_HASH_ENTRY_EMPTY = 0xFFFFFFFF
_HASH_ENTRY_DELETED = 0xFFFFFFFE

# Hash types, selecting which quarter of the crypt table to use
_HASH_TABLE_OFFSET = 0
_HASH_NAME_A = 1
_HASH_NAME_B = 2
_HASH_FILE_KEY = 3


class MpqError(Exception):
    """The archive is malformed, or uses something not implemented here."""


def _build_crypt_table() -> list[int]:
    """Blizzard's 0x500-entry table, generated by a fixed linear congruence."""
    table = [0] * 0x500
    seed = 0x00100001
    for index1 in range(0x100):
        index2 = index1
        for _ in range(5):
            seed = (seed * 125 + 3) % 0x2AAAAB
            temp1 = (seed & 0xFFFF) << 16
            seed = (seed * 125 + 3) % 0x2AAAAB
            temp2 = seed & 0xFFFF
            table[index2] = temp1 | temp2
            index2 += 0x100
    return table


_CRYPT = _build_crypt_table()


def _hash(text: str, hash_type: int) -> int:
    """Blizzard's string hash. Case-insensitive; backslash is the separator."""
    seed1 = 0x7FED7FED
    seed2 = 0xEEEEEEEE
    for char in text.upper():
        value = ord(char)
        seed1 = _CRYPT[(hash_type << 8) + value] ^ ((seed1 + seed2) & 0xFFFFFFFF)
        seed2 = (value + seed1 + seed2 + (seed2 << 5) + 3) & 0xFFFFFFFF
    return seed1


def _decrypt(data: bytes, key: int) -> bytes:
    """Decrypt a whole number of 32-bit words. Trailing odd bytes pass through."""
    seed1 = key & 0xFFFFFFFF
    seed2 = 0xEEEEEEEE
    words = len(data) // 4
    out = bytearray(data)
    for index in range(words):
        seed2 = (seed2 + _CRYPT[0x400 + (seed1 & 0xFF)]) & 0xFFFFFFFF
        (raw,) = struct.unpack_from("<I", data, index * 4)
        value = (raw ^ ((seed1 + seed2) & 0xFFFFFFFF)) & 0xFFFFFFFF
        seed1 = (
            (((~seed1) & 0xFFFFFFFF) << 0x15) + 0x11111111 | (seed1 >> 0x0B)
        ) & 0xFFFFFFFF
        seed2 = (value + seed2 + (seed2 << 5) + 3) & 0xFFFFFFFF
        struct.pack_into("<I", out, index * 4, value)
    return bytes(out)


def _encrypt(data: bytes, key: int) -> bytes:
    """The inverse of :func:`_decrypt`.

    The two differ in one place that is easy to get wrong: ``seed2`` is advanced
    from the **plaintext** word in both directions. Decryption happens to have
    the plaintext in hand as its result, so the update looks like it uses the
    output; here it must explicitly use the input.
    """
    seed1 = key & 0xFFFFFFFF
    seed2 = 0xEEEEEEEE
    words = len(data) // 4
    out = bytearray(data)
    for index in range(words):
        seed2 = (seed2 + _CRYPT[0x400 + (seed1 & 0xFF)]) & 0xFFFFFFFF
        (plain,) = struct.unpack_from("<I", data, index * 4)
        cipher = (plain ^ ((seed1 + seed2) & 0xFFFFFFFF)) & 0xFFFFFFFF
        seed1 = (
            (((~seed1) & 0xFFFFFFFF) << 0x15) + 0x11111111 | (seed1 >> 0x0B)
        ) & 0xFFFFFFFF
        seed2 = (plain + seed2 + (seed2 << 5) + 3) & 0xFFFFFFFF
        struct.pack_into("<I", out, index * 4, cipher)
    return bytes(out)


def looks_like_mpq(raw: bytes) -> bool:
    return raw[:4] in (MPQ_MAGIC, _USERDATA_MAGIC)


@dataclass(frozen=True, slots=True)
class _Block:
    offset: int
    packed_size: int
    unpacked_size: int
    flags: int

    @property
    def exists(self) -> bool:
        return bool(self.flags & FLAG_EXISTS) and not (self.flags & FLAG_DELETE_MARKER)


@dataclass(frozen=True, slots=True)
class _HashEntry:
    name_a: int
    name_b: int
    locale: int
    platform: int
    block_index: int


def _decompress(data: bytes, expected: int, flags: int) -> bytes:
    """Undo whatever compression a sector carries."""
    if len(data) >= expected:
        # A sector is only stored compressed when compression actually saved
        # something, so an unshrunken sector is stored verbatim.
        return data[:expected]

    if flags & FLAG_IMPLODE and not (flags & FLAG_COMPRESS):
        # The IMPLODE flag means the whole file is PKWARE-imploded and there is
        # no leading method byte.
        return explode(data, expected)

    method = data[0]
    payload = data[1:]
    if method == 0:
        return payload
    if method == COMP_ZLIB:
        return zlib.decompress(payload)
    if method == COMP_PKWARE:
        return explode(payload, expected)
    if method == COMP_BZIP2:
        return bz2.decompress(payload)
    raise MpqError(
        f"unsupported compression method 0x{method:02x}; "
        "only none, zlib, pkware and bzip2 are implemented"
    )


class MpqArchive:
    """A read-only view of an MPQ archive held in memory."""

    def __init__(self, raw: bytes) -> None:
        self._raw = raw
        self._base = self._find_header(raw)
        header = _HEADER.unpack_from(raw, self._base)
        (
            magic,
            self.header_size,
            self.archive_size,
            self.format_version,
            self.sector_shift,
            hash_table_offset,
            block_table_offset,
            hash_table_size,
            block_table_size,
        ) = header
        if magic != MPQ_MAGIC:
            raise MpqError("not an MPQ archive")
        # formatVersion 0 is MPQ v1; 1 is v2, which adds a hi-block table and
        # 64-bit offsets that nothing here reads. Refusing is the honest option:
        # a v2 archive parsed as v1 yields plausible-looking wrong bytes. Every
        # StarCraft map found so far is v1.
        if self.format_version != 0:
            raise MpqError(
                f"MPQ format version {self.format_version + 1} is not supported; "
                "only v1 archives can be read, which is what StarCraft maps are"
            )
        self.sector_size = 512 << self.sector_shift
        #: Notes about declared table sizes that had to be clamped -- a strong
        #: signal that the map has been deliberately protected.
        self.clamped_tables: list[str] = []
        #: True when a file was found only by scanning the whole hash table.
        self.recovered_by_scan = False
        self._hash_table = self._read_hash_table(hash_table_offset, hash_table_size)
        self._block_table = self._read_block_table(block_table_offset, block_table_size)

    # -- construction ------------------------------------------------------

    @classmethod
    def from_path(cls, path) -> "MpqArchive":
        with open(path, "rb") as handle:
            return cls(handle.read())

    @staticmethod
    def _find_header(raw: bytes) -> int:
        """MPQ data may be preceded by other content, aligned to 512 bytes."""
        if raw[:4] == MPQ_MAGIC:
            return 0
        for offset in range(0, len(raw) - _HEADER.size, _ALIGN):
            if raw[offset : offset + 4] == MPQ_MAGIC:
                return offset
            if raw[offset : offset + 4] == _USERDATA_MAGIC:
                # A user-data header carries the offset of the real one:
                # magic, userDataSize, mpqHeaderOffset, userDataHeaderSize.
                _, _, header_offset, _ = struct.unpack_from("<4sIII", raw, offset)
                return offset + header_offset
        raise MpqError("no MPQ header found")

    def _table(self, offset: int, count: int, entry_size: int,
               key_name: str) -> tuple[bytes, int]:
        """Decrypt a table, clamping a declared count that cannot fit.

        Map protectors routinely inflate the declared table size -- setting
        ``hashTableSize`` to 0x10000400 rather than 0x400 is a standard trick,
        and a reader that trusts it refuses the map. The number of entries the
        file can physically hold is authoritative, so the declared count is only
        an upper bound.
        """
        start = self._base + offset
        available = max(len(self._raw) - start, 0) // entry_size
        if available == 0:
            raise MpqError(f"{key_name} starts past the end of the file")
        if count > available:
            self.clamped_tables.append(
                f"{key_name} declares {count} entries but only {available} fit"
            )
            count = available
        size = count * entry_size
        data = _decrypt(self._raw[start : start + size], _hash(key_name, _HASH_FILE_KEY))
        return data, count

    def _read_hash_table(self, offset: int, count: int) -> list[_HashEntry]:
        data, count = self._table(offset, count, _HASH_ENTRY_SIZE, "(hash table)")
        return [
            _HashEntry(*_HASH_ENTRY.unpack_from(data, i * _HASH_ENTRY_SIZE))
            for i in range(count)
        ]

    def _read_block_table(self, offset: int, count: int) -> list[_Block]:
        data, count = self._table(offset, count, _BLOCK_ENTRY_SIZE, "(block table)")
        return [
            _Block(*_BLOCK_ENTRY.unpack_from(data, i * _BLOCK_ENTRY_SIZE))
            for i in range(count)
        ]

    # -- lookup ------------------------------------------------------------

    def _find(self, filename: str) -> _HashEntry | None:
        """Locate a file's hash entry by linear probing from its home slot."""
        count = len(self._hash_table)
        if count == 0:
            return None
        start = _hash(filename, _HASH_TABLE_OFFSET) % count
        name_a = _hash(filename, _HASH_NAME_A)
        name_b = _hash(filename, _HASH_NAME_B)
        for step in range(count):
            entry = self._hash_table[(start + step) % count]
            if entry.block_index == _HASH_ENTRY_EMPTY:
                break        # never occupied: the probe chain ends here
            if entry.block_index == _HASH_ENTRY_DELETED:
                continue     # tombstone: keep probing
            if entry.name_a == name_a and entry.name_b == name_b:
                return entry

        # The probe assumes an entry sits at or after its home slot, which holds
        # only when the table size matches the one used to insert it. Protectors
        # break that by lying about the size, so fall back to a full scan. The
        # name hashes are still a 64-bit match, so this stays specific.
        for entry in self._hash_table:
            if entry.block_index in (_HASH_ENTRY_EMPTY, _HASH_ENTRY_DELETED):
                continue
            if entry.name_a == name_a and entry.name_b == name_b:
                self.recovered_by_scan = True
                return entry
        return None

    def __contains__(self, filename: str) -> bool:
        entry = self._find(filename)
        if entry is None or entry.block_index >= len(self._block_table):
            return False
        return self._block_table[entry.block_index].exists

    def read_file(self, filename: str) -> bytes:
        """Extract one file by name. Raises :class:`MpqError` if absent."""
        entry = self._find(filename)
        if entry is None:
            raise MpqError(f"{filename!r} is not in this archive")
        if entry.block_index >= len(self._block_table):
            raise MpqError(f"{filename!r} points at block {entry.block_index}, out of range")
        block = self._block_table[entry.block_index]
        if not block.exists:
            raise MpqError(f"{filename!r} is present but marked deleted")
        return self._read_block(block, filename)

    # -- extraction --------------------------------------------------------

    def _file_key(self, block: _Block, filename: str) -> int:
        """The decryption key, derived from the base name, not the full path."""
        base = filename.rsplit("\\", 1)[-1].rsplit("/", 1)[-1]
        key = _hash(base, _HASH_FILE_KEY)
        if block.flags & FLAG_FIX_KEY:
            # The key is adjusted by where the file sits and how big it is, so
            # the same name in two archives does not share a key.
            key = ((key + block.offset) ^ block.unpacked_size) & 0xFFFFFFFF
        return key

    def _read_block(self, block: _Block, filename: str) -> bytes:
        start = self._base + block.offset
        packed = self._raw[start : start + block.packed_size]
        if len(packed) < block.packed_size:
            raise MpqError(f"{filename!r} runs past the end of the file")

        encrypted = bool(block.flags & FLAG_ENCRYPTED)
        key = self._file_key(block, filename) if encrypted else 0
        compressed = bool(block.flags & (FLAG_COMPRESS | FLAG_IMPLODE))

        if block.flags & FLAG_SINGLE_UNIT:
            if encrypted:
                packed = _decrypt(packed, key)
            if not compressed:
                return packed[: block.unpacked_size]
            return _decompress(packed, block.unpacked_size, block.flags)

        if not compressed:
            # Stored flat, but still sector-encrypted if the file is encrypted.
            if not encrypted:
                return packed[: block.unpacked_size]
            out = bytearray()
            for index, (begin, end) in enumerate(
                self._flat_sectors(block.unpacked_size)
            ):
                out += _decrypt(packed[begin:end], (key + index) & 0xFFFFFFFF)
            return bytes(out[: block.unpacked_size])

        return self._read_sectors(packed, block, key, encrypted)

    def _flat_sectors(self, size: int) -> Iterator[tuple[int, int]]:
        for offset in range(0, size, self.sector_size):
            yield offset, min(offset + self.sector_size, size)

    def _read_sectors(self, packed: bytes, block: _Block, key: int,
                      encrypted: bool) -> bytes:
        sector_count = -(-block.unpacked_size // self.sector_size)
        # One offset per sector plus a terminator, and one more when the archive
        # stores a CRC sector after the data.
        entries = sector_count + 1
        if block.flags & FLAG_SECTOR_CRC:
            entries += 1
        table_size = entries * 4
        if table_size > len(packed):
            raise MpqError("sector offset table runs past the block")

        table = packed[:table_size]
        if encrypted:
            # The offset table is encrypted with the file key minus one.
            table = _decrypt(table, (key - 1) & 0xFFFFFFFF)
        offsets = list(struct.unpack(f"<{entries}I", table))

        out = bytearray()
        for index in range(sector_count):
            begin, end = offsets[index], offsets[index + 1]
            if not (0 <= begin <= end <= len(packed)):
                raise MpqError(
                    f"sector {index} offsets {begin}..{end} lie outside the block"
                )
            sector = packed[begin:end]
            if encrypted:
                sector = _decrypt(sector, (key + index) & 0xFFFFFFFF)
            remaining = block.unpacked_size - len(out)
            expected = min(self.sector_size, remaining)
            out += _decompress(sector, expected, block.flags)
        return bytes(out[: block.unpacked_size])

    # -- introspection -----------------------------------------------------

    @property
    def block_count(self) -> int:
        return len(self._block_table)

    @property
    def hash_slot_count(self) -> int:
        return len(self._hash_table)

    def block_flags(self) -> list[int]:
        """Flags of every block, for diagnostics."""
        return [b.flags for b in self._block_table]


class MpqWriter:
    """Build a small MPQ v1 archive -- enough to save a map.

    The archive layout is header, then file data, then the hash table, then the
    block table, which is what every StarCraft map uses.

    Files are stored **uncompressed by default**, and that is a deliberate
    choice rather than laziness. StarCraft 1.16.1 ships an old Storm build, and
    which compressions it accepts is not something this project can verify
    without launching the game. Storing plainly is accepted by every reader that
    exists. ``compress=True`` opts into zlib per sector, which StormLib reads
    happily but which has not been confirmed against the retail client.

    Nothing is encrypted on write. Encryption exists to make files hard to pull
    out of an archive; it buys a map editor nothing and only adds ways to
    produce something unreadable.
    """

    #: Empty hash slots are all-ones, which is what makes ``block_index`` read
    #: back as ``_HASH_ENTRY_EMPTY``.
    _EMPTY_HASH_ENTRY = b"\xff" * _HASH_ENTRY_SIZE

    def __init__(self, *, sector_shift: int = 3, hash_table_size: int | None = None,
                 listfile: bool = True) -> None:
        if not 0 <= sector_shift <= 23:
            raise MpqError(f"sector_shift {sector_shift} is out of range")
        self.sector_shift = sector_shift
        self.sector_size = 512 << sector_shift
        self._requested_hash_size = hash_table_size
        self._listfile = listfile
        self._files: list[tuple[str, bytes, bool]] = []

    def add(self, name: str, data: bytes, *, compress: bool = False) -> None:
        """Queue a file. ``name`` uses backslashes, as MPQ paths do."""
        if any(existing == name for existing, _, _ in self._files):
            raise MpqError(f"{name!r} was already added")
        self._files.append((name, bytes(data), compress))

    # -- layout ------------------------------------------------------------

    def _hash_table_size(self, file_count: int) -> int:
        """A power of two with headroom, because probing degrades when full."""
        if self._requested_hash_size is not None:
            size = self._requested_hash_size
            if size < 1 or size & (size - 1):
                raise MpqError(f"hash_table_size {size} is not a power of two")
            if size < file_count:
                raise MpqError(
                    f"hash_table_size {size} cannot hold {file_count} files"
                )
            return size
        size = 16
        while size < file_count * 2:
            size *= 2
        return size

    def _pack_file(self, data: bytes, compress: bool) -> tuple[bytes, int]:
        """Return the stored bytes and the block flags for one file."""
        if not compress or not data:
            return data, FLAG_EXISTS

        sectors = [
            data[offset : offset + self.sector_size]
            for offset in range(0, len(data), self.sector_size)
        ]
        packed: list[bytes] = []
        for sector in sectors:
            candidate = bytes((COMP_ZLIB,)) + zlib.compress(sector, 9)
            # A sector is only stored compressed when that actually gained
            # something; otherwise it goes in raw and the reader detects it by
            # the stored size matching the unpacked size.
            packed.append(candidate if len(candidate) < len(sector) else sector)

        table_size = (len(sectors) + 1) * 4
        offsets = [table_size]
        for sector in packed:
            offsets.append(offsets[-1] + len(sector))
        blob = struct.pack(f"<{len(offsets)}I", *offsets) + b"".join(packed)
        if len(blob) >= len(data):
            # Compression made it bigger. Store plainly instead.
            return data, FLAG_EXISTS
        return blob, FLAG_EXISTS | FLAG_COMPRESS

    def to_bytes(self) -> bytes:
        files = list(self._files)
        if self._listfile and files:
            names = "\r\n".join(name for name, _, _ in files) + "\r\n"
            files.append(("(listfile)", names.encode("ascii"), False))
        if not files:
            raise MpqError("an archive needs at least one file")

        hash_size = self._hash_table_size(len(files))
        header_size = _HEADER.size

        # Lay the file data out immediately after the header.
        blocks: list[tuple[int, int, int, int]] = []
        blob = bytearray()
        for _, data, compress in files:
            stored, flags = self._pack_file(data, compress)
            blocks.append((header_size + len(blob), len(stored), len(data), flags))
            blob += stored

        hash_offset = header_size + len(blob)
        block_offset = hash_offset + hash_size * _HASH_ENTRY_SIZE
        archive_size = block_offset + len(files) * _BLOCK_ENTRY_SIZE

        hash_table = self._build_hash_table(files, hash_size)
        block_table = b"".join(_BLOCK_ENTRY.pack(*entry) for entry in blocks)

        header = _HEADER.pack(
            MPQ_MAGIC, header_size, archive_size, 0, self.sector_shift,
            hash_offset, block_offset, hash_size, len(files),
        )
        return (
            header
            + bytes(blob)
            + _encrypt(hash_table, _hash("(hash table)", _HASH_FILE_KEY))
            + _encrypt(block_table, _hash("(block table)", _HASH_FILE_KEY))
        )

    def _build_hash_table(self, files, hash_size: int) -> bytes:
        table = bytearray(self._EMPTY_HASH_ENTRY * hash_size)
        for block_index, (name, _, _) in enumerate(files):
            slot = _hash(name, _HASH_TABLE_OFFSET) % hash_size
            for step in range(hash_size):
                probe = (slot + step) % hash_size
                start = probe * _HASH_ENTRY_SIZE
                if table[start : start + _HASH_ENTRY_SIZE] == self._EMPTY_HASH_ENTRY:
                    _HASH_ENTRY.pack_into(
                        table, start,
                        _hash(name, _HASH_NAME_A),
                        _hash(name, _HASH_NAME_B),
                        0,   # locale: neutral
                        0,   # platform
                        block_index,
                    )
                    break
            else:  # pragma: no cover - guarded by _hash_table_size
                raise MpqError("hash table is full")
        return bytes(table)


def write_scenario(chk: bytes, *, compress: bool = False, **kwargs) -> bytes:
    """Build a map archive containing ``chk`` as ``staredit\\scenario.chk``."""
    writer = MpqWriter(**kwargs)
    writer.add(SCENARIO_PATH, chk, compress=compress)
    return writer.to_bytes()


def read_scenario(raw: bytes) -> bytes:
    """Pull ``staredit\\scenario.chk`` out of a map archive.

    Some maps carry a decoy scenario under the neutral locale and the real one
    under 0x409; that is a protection technique rather than a format variant.
    Only the straightforward case is handled here -- a decoy shows up as an
    implausibly small CHK, which the caller can notice.
    """
    return MpqArchive(raw).read_file(SCENARIO_PATH)
